/**
 * Bit.ly Clone
 * Bit.ly clone API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetLongLinkResponse } from './getLongLinkResponse';

export interface GetLongLinkResponseResDto { 
    /**
     * Flag of success
     */
    success: boolean;
    /**
     * Response Body
     */
    body: GetLongLinkResponse;
}