/**
 * Bit.ly Clone
 * Bit.ly clone API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LinkViewsByDay } from './linkViewsByDay';

export interface LinkViewsByDayResponse { 
    /**
     * Link statistic
     */
    linkStatistic: Array<LinkViewsByDay>;
}