/**
 * Bit.ly Clone
 * Bit.ly clone API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AddLinkRequest } from '../model/addLinkRequest';
import { AddLinkResponseResDto } from '../model/addLinkResponseResDto';
import { GetLongLinkResponseResDto } from '../model/getLongLinkResponseResDto';
import { LinkViewsByDayResponseResDto } from '../model/linkViewsByDayResponseResDto';
import { UserLinkResponseResDto } from '../model/userLinkResponseResDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class LinksService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public linksControllerFindUserLinks(observe?: 'body', reportProgress?: boolean): Observable<UserLinkResponseResDto>;
    public linksControllerFindUserLinks(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserLinkResponseResDto>>;
    public linksControllerFindUserLinks(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserLinkResponseResDto>>;
    public linksControllerFindUserLinks(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<UserLinkResponseResDto>('get',`${this.basePath}/api/links/user-links`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public linksControllerGenerateShortLink(body: AddLinkRequest, observe?: 'body', reportProgress?: boolean): Observable<AddLinkResponseResDto>;
    public linksControllerGenerateShortLink(body: AddLinkRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AddLinkResponseResDto>>;
    public linksControllerGenerateShortLink(body: AddLinkRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AddLinkResponseResDto>>;
    public linksControllerGenerateShortLink(body: AddLinkRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling linksControllerGenerateShortLink.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<AddLinkResponseResDto>('post',`${this.basePath}/api/links`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param code 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public linksControllerGetDayLinkDayStatistic(code: string, observe?: 'body', reportProgress?: boolean): Observable<LinkViewsByDayResponseResDto>;
    public linksControllerGetDayLinkDayStatistic(code: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LinkViewsByDayResponseResDto>>;
    public linksControllerGetDayLinkDayStatistic(code: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LinkViewsByDayResponseResDto>>;
    public linksControllerGetDayLinkDayStatistic(code: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (code === null || code === undefined) {
            throw new Error('Required parameter code was null or undefined when calling linksControllerGetDayLinkDayStatistic.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<LinkViewsByDayResponseResDto>('get',`${this.basePath}/api/links/statistic/${encodeURIComponent(String(code))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param code 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public linksControllerGetLinkByCode(code: string, observe?: 'body', reportProgress?: boolean): Observable<GetLongLinkResponseResDto>;
    public linksControllerGetLinkByCode(code: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetLongLinkResponseResDto>>;
    public linksControllerGetLinkByCode(code: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetLongLinkResponseResDto>>;
    public linksControllerGetLinkByCode(code: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (code === null || code === undefined) {
            throw new Error('Required parameter code was null or undefined when calling linksControllerGetLinkByCode.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<GetLongLinkResponseResDto>('get',`${this.basePath}/api/links/long-link/${encodeURIComponent(String(code))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
